# Generated by Django 5.0 on 2023-12-19 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='manufacture_date',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='manufacture_year',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000)]),
            preserve_default=False,
        ),
    ]
