# Generated by Django 5.0 on 2023-12-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationApp', '0002_remove_vehicle_manufacture_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='country',
            field=models.CharField(default=2000, max_length=255),
            preserve_default=False,
        ),
    ]
