# Generated by Django 5.0 on 2023-12-19 17:01

import ValidationApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationApp', '0003_vehicle_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plates', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Plate number must start with RAA-RAH', regex='^R[A-H]\\d{1,3}_z$')])),
                ('make', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=15)),
                ('man_date', models.DateField(validators=[ValidationApp.models.Vehicles.validate_manufact_year_2000])),
                ('car_type', models.CharField(choices=[('p', 'personal'), ('non', 'non_personal'), ('O', 'Other')], max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
