# Generated by Django 5.0 on 2023-12-19 17:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationApp', '0004_vehicles_delete_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='ValidationApp.participant'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='plates',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Plate number must be in correct format', regex='^R[A-H]\\d{1,3}_z$')]),
        ),
    ]
