# Generated by Django 5.0 on 2023-12-20 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationApp', '0005_vehicles_participant_alter_vehicles_plates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='plates',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Plate number must be in correct form', regex='^((R[A-Z][A-H]\\d{1,3}[A-Z])|(RNP\\d{1,3}[A-Z])|(RDF\\d{1,3}[A-Z])) |(CD\\d{1,3}[A-Z])) |(IT\\d{1,3}[A-Z])) |(GR\\d{1,3}[A-Z]))$')]),
        ),
    ]
